# Config
# ========================================================================================

url:                   https://RongKaiWeskerMA.github.io
baseurl:               ''
lang:                  en
title:                 Rongkai Ma 马熔锴

description:           >
  Rongkai at NVIDIA

tagline:               >
  Senior Machine Learning Engineer, NVIDIA (Deep Learning Toolkit Development)

keywords:              []

# Used by jekyll-seo-tag.
logo:                  /assets/img/me.jpg

author:
  name:                Rongkai Ma
  picture:             /assets/img/me.jpg
  social:
    email:              'rongkaim@nvidia.com'
    github:             RongKaiWeskerMA

copyright:             >

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /page-:num/


# Customization
# ========================================================================================

# Hero background image
accent_image:          /assets/img/sidebar-bg.jpg


# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md


# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


# Plugin Configuration
# ========================================================================================

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true
